
GET http://localhost:3000/api/usuarios/2

###

DELETE http://localhost:3000/api/usuarios/6
###

###
POST http://localhost:3000/api/usuariosTatuadores/1/moreData
Content-Type: application/json

{
    "imgPerfil": "kk",
    "estilos":[1, 2],
    "sobreMi": ""
}

###
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "nombre": "Khris Sanchez Romero",
    "sexo":"femenino",
    "direccion": "Calle del olvido",
    "ciudad": "Madrid",
    "cp": "28025",
    "telefono": "654882318",
    "fechaNacimiento":"1998/06/09",
    "nombreUsuario":"Khris",
    "email":"khris@gmail.com",
    "password":"987655",
    "repetirPassword":"987656",
    "tatuador":"No",
    "proteccionDatos":"Acepto"

}

###
PUT http://localhost:3000/api/usuarios/21
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyMywiY2FkdWNpZGFkIjoxNjI1NDEyOTUxLCJpYXQiOjE2MjQ4MDgxNTF9.AB3GNCrELWRpi5eLsUPNfYikkmPSrLdOPMyCvxWP_Q8

{
    "nombre": "Ana Martin",
    "direccion": "Calle del olvido",
    "ciudad": "Madrid",
    "cp": "28025",
    "telefono": "654882318",
    "email":"cecimierdas@gmail.com",
    "password":"23145"
}

###

GET http://localhost:3000/api/usuarios/3/favs

###
GET http://localhost:3000/api/usuariosTatuadores

###
GET http://localhost:3000/api/usuariosTatuadores?wildcard=exp&estilo=Animacion

###

GET http://localhost:3000/api/usuariosTatuadores/3

###

GET http://localhost:3000/api/usuariosTatuadores/1/pics

###

GET http://localhost:3000/api/usuariosTatuadores/6/pics

###


//Enviar gracias al token al perfil del id del usuario
GET http://localhost:3000/api/usuarios/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoyMiwiY2FkdWNpZGFkIjoxNjI1MTU0NjAyLCJpYXQiOjE2MjQ1NDk4MDJ9.fn3ocwMRV0nO4axaSdPaeisDEChvB5ZJvhlgzxyidjg

###

POST http://localhost:3000/api/usuariosTatuadores/4/pics
Content-Type: application/json

{
    "imagen": "https://scontent-mad1-1.xx.fbcdn.net/v/t1.6435-9/178017352_1420777094955619_1346208378682206340_n.jpg?_nc_cat=110&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=11Cqo8-jU4IAX-GpanF&_nc_ht=scontent-mad1-1.xx&oh=39e31d60801fabfd79a1ce9cda1fc717&oe=60D06F45",
    "estilo": 10
    
}

###

DELETE http://localhost:3000/api/usuariosTatuadores/4/pics/26


###

POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
"email" : "khris@gmail.com",
"password": "987655"
}


###

POST http://localhost:3000/api/usuariosTatuadores/1/tatuajes/upload
Content-Type: application/json

{
    "fk_usuario_tatuador_id": 2,
    "file": "miau.svg"
}




