GET http://localhost:3000/api/usuarios/

###

GET http://localhost:3000/api/usuarios/2

###

DELETE http://localhost:3000/api/usuarios/6

###

















POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "nombre": "Cecilia Martin",
    "sexo":"femenino",
    "direccion": "Calle del olvido",
    "ciudad": "Madrid",
    "cp": "28025",
    "telefono": "654882318",
    "fechaNacimiento":"1998-06-09",
    "nombreUsuario":"CeciM",
    "email":"cecim@gmail.com",
    "password":"987655",
    "repetirPassword":"987655",
    "tatuador":"No",
    "proteccionDatos":"Acepto"

}

###
